version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT
      - "61613:61613"  # STOMP
      - "4369:4369"    # EPMD
      - "25672:25672"  # Clustering
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODENAME: rabbit@localhost
    command: [
      "bash", "-c",
      "chmod 400 /var/lib/rabbitmq/.erlang.cookie; 
      rabbitmq-plugins enable rabbitmq_management;
      rabbitmq-plugins enable rabbitmq_stomp;
      rabbitmq-server" ]
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456a@
      POSTGRES_DB: web-chat
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/web-chat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456a@
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  rabbitmq_data:
  pg_data:
